version: '3'
services:
  web:
    stdin_open: true
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
  tests:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ['npm', 'run', 'test']
# this ports was menntioned to get access from our system. with the docker compose, containers can automatially connect to each otehr
