sudo: required
services:
  - docker

before_install:
  - docker build -t umeshbhat/dockerk8s -f Dockerfile.dev .

script:
  - docker run -e CI=true umeshbhat/dockerk8s npm run test

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-us-east-2-664592431862'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    $AWS_SECRET_KEY
    # DockerReact-env.eba-bm3j6ruf.us-east-2.elasticbeanstalk.com
