version: '3'
services:
  redis-server:
    image: 'redis'
  node-app:
    restart: always
    build: .
    ports:
      - '4001:8081'
# this ports was menntioned to get access from our system. with the docker compose, containers can automatially connect to each otehr
